spring:
  application:
    name: arthur-config-center
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    default-property-inclusion: non_null
  #配置中心 GitHub配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ArthurFamily/arthur.git
          search-paths: /dev
          strict-host-key-checking: false
#  thymeleaf:
#    mode: LEGACYHTML5
#    prefix: classpath:/WEB-INF/view/
#  mvc:
#    static-path-pattern: /static/**
#  jpa:
#    hibernate:
 #     ddl-auto: none
 #   show-sql: true
#version: v{(\\d)+}
#mybatis:
#  mapper-locations: classpath:mybatis/**/*.xml
#  config-location: classpath:mybatis-config.xml
server:
  port: 10002
  #context-path: /web

# 注册中心
eureka:
  client:
    enabled: true
    #注册中心开启健康检查会刷新上下文
    healthcheck:
        enabled: false
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    serviceUrl:
        defaultZone: http://${eurekaCenter.username}:${eurekaCenter.pasword}@localhost:8761/eureka/
  instance:
      appname: ${spring.application.name}
      instanceId: ${spring.application.name}:${spring.application.instance-id:${random.value}:${server.port}}
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 10
      status-page-url-path: ${management.context-path}/info
      health-check-url-path: ${management.context-path}/health
      metadata-map:
          zone: primary
          profile: ${spring.profiles.active}
          version: ${info.project.version}
# 配置中心
eurekaCenter:
  username: admin
  pasword: admin

#develop
# zuul配置
zuul:
    host:
        max-total-connections: 1000
        max-per-route-connections: 100
    semaphore:
        max-semaphores: 500

# 熔断器配置
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 10000
#前端负载配置
ribbon:
  eureka:
    enabled: true

# 健康监控中心配置
management:
    security:
        roles: ADMIN
    context-path: /management
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
#版本
info:
  project:
    version: v1

